some:
    common:
        config:
            item: hello world, let's hold hands.
---
spring:
    config:
        activate:
            on-profile: prod
    
my_app:
    system:
        first_key: This is from the prod profile.
        second_key: 3.14
        third_key: 42

---
spring:
    config:
        activate:
            on-profile: uat
    
my_app:
    system:
        first_key: This is from the uat profile.
        second_key: 3.333333
        third_key: 99

---
